// FulcrumDemoEN.typ
//
// English (FulcrumEN) CNL template demonstration.
// Compile from this directory:
//   typst compile FulcrumDemoEN.typ FulcrumDemoEN.pdf
//
// This document showcases:
//   - 9 entryEN-based blocks: definition, theorem, lemma, proposition,
//     structure, example, remark, variable_block, instance_block
//   - 5 declare-class clauses: declare, structure_declare, theorem_declare,
//     instance_declare, structure_instance_declare
//   - The doc_remark helper
//   - 8 short bilingual-title aliases: axm, rule, dfn, struct, ppt, thm,
//     xmp, rmk
//
// All English-side primitives live in FulcrumEN.typ; users access them
// transparently through `#import "Fulcrum.typ": *`.


#import "Fulcrum.typ": *

#show: FulcrumCN

#set document(title: "Fulcrum English CNL Template — Command Demo")

#align(center)[
  #text(size: 1.6em, weight: "bold")[
    Fulcrum English CNL Template \ Command Demo
  ]
  #v(0.5em)
  #text(size: 0.9em, fill: gray)[
    Showcase of all `entryEN`-based blocks, declare clauses, and short aliases.
  ]
]

#v(1em)


= Design Overview

The English layer mirrors the Chinese layer at the API surface but uses a
single English title (no dual-language). Each block is produced by
`entryEN(...)`. CNL clauses (`declare`, `theorem_declare`,
`structure_declare`, `instance_declare`, `structure_instance_declare`)
provide the natural-language structure inside the entry body.


= Entry blocks (`entryEN`-based)

Each block here uses one declare clause as its body to keep the demo focused.


== `definition` (green)

#definition("Linear Space")[
  #declare(
    hypotheses: ([$KK$ is a field],),
    type: [Type],
    notation: [$(V, +, dot)$],
  )[$KK$-linear space][
    a set $V$ together with addition $+ : V times V -> V$ and scalar
    multiplication $dot : KK times V -> V$ satisfying the usual axioms.
  ]
]


== `theorem` (blue)

#theorem("Maschke")[
  #theorem_declare(
    hypotheses: ([$G$ is a finite group], [$KK$ is a field whose characteristic does not divide $|G|$]),
  )[every finite-dimensional $KK$-representation of $G$ is completely reducible]
]


== `lemma` (blue, shares `theorem` counter)

#lemma("Zorn")[
  #theorem_declare(
    hypotheses: ([$P$ is a non-empty poset], [every chain in $P$ has an upper bound]),
  )[$P$ contains a maximal element]
]


== `proposition` (blue)

#proposition("Cyclic groups are abelian")[
  #theorem_declare()[every cyclic group is abelian]
]


== `structure` (orange)

#structure("Group")[
  #structure_declare(
    fields: (
      ([carrier], "carrier", [Type]),
      ([multiplication], "mul", [carrier $times$ carrier $->$ carrier]),
      ([identity], "one", [carrier]),
      ([inverse], "inv", [carrier $->$ carrier]),
    ),
  )[Group]
]


== `example` (purple)

#example("$RR^n$ as a real linear space")[
  $RR^n$ with componentwise addition and componentwise scalar
  multiplication forms an $RR$-linear space whose zero vector is
  $(0, ..., 0)$.
]


== `remark` (grey)

#remark("On notation")[
  Throughout this document, we use $bold(0)$ for the zero vector of a
  linear space to distinguish it from the scalar $0 in KK$. In contexts
  where there is no ambiguity, the boldface may be dropped.
]


== `variable_block` (light grey)

Used to declare a section's implicit variables — these don't have a
mathematical body, just a list of variables in scope.

#variable_block("Variables in this section")[
  $KK$ is a field of characteristic zero. $V$ is a finite-dimensional
  $KK$-linear space.
]


== `instance_block` (teal) + `instance_declare`

The `instance_declare` clause has three styles. We show the most common
one (`carries`):

#instance_block("Symmetric group action on tableaux")[
  #instance_declare(
    [a #raw("MulAction") $S_n$ structure],
    [the type #raw("StandardYoungTableau") $lambda$],
    [for $sigma in S_n$ and $T$ a standard Young tableau of shape
     $lambda$, the action $sigma dot T$ is the tableau whose entry at
     cell $c$ is $sigma(T."entry" c)$],
    style: "action",
  )
]

The `is`-style flavor for predicate-shaped bodies:

#instance_block("Integers form a CommRing")[
  #instance_declare(
    [#raw("CommRing")],
    [$ZZ$],
    [is a commutative ring under standard integer addition and multiplication],
    style: "is",
  )
]


= Declare clauses

`declare` clauses live *inside* an entry body and produce the CNL prose.


== `#declare` — definition clause

Plain definition with hypotheses, type, and notation:

#definition("Tensor product space")[
  #declare(
    hypotheses: ([$KK$ is a field], [$V, W$ are $KK$-linear spaces]),
    type: [$KK$-linear space],
    notation: [$V times.o_KK W$],
  )[the tensor product of $V$ and $W$][
    the $KK$-linear space generated by elements of the form
    $bold(v) times.o bold(w)$ subject to the bilinearity relations.
  ]
]

Predicate definition (`isPredicate: true`):

#definition("Linear independence")[
  #declare(
    hypotheses: ([$V$ is a $KK$-linear space], [$bold(v)_1, ..., bold(v)_n in V$]),
    isPredicate: true,
  )[$bold(v)_1, ..., bold(v)_n$ are linearly independent][
    $sum_(i=1)^n a_i bold(v)_i = bold(0)$ implies $a_1 = ... = a_n = 0$.
  ]
]


== `#structure_declare` — Lean structure declaration

#structure("Linear space")[
  #structure_declare(
    hypotheses: ([$KK$ is a field],),
    fields: (
      ([carrier], "carrier", [Type]),
      ([addition], "add", [carrier $times$ carrier $->$ carrier]),
      ([scalar multiplication], "smul", [$KK times$ carrier $->$ carrier]),
      ([zero], "zero", [carrier]),
      ([axioms…], "axioms", [vector space axioms]),
    ),
  )[$KK$-linear space]

  #doc_remark[
    Mathlib spells this as `Module KK V` where `V` is an additive
    abelian group. We use the more elementary "structure with axiom
    fields" presentation here for readability.
  ]
]


== `#theorem_declare` — theorem clause

Without hypotheses (clean conclusion):

#proposition("Identity uniqueness")[
  #theorem_declare()[the identity element of a group is unique]
]

With hypotheses:

#theorem("Lagrange")[
  #theorem_declare(
    hypotheses: ([$G$ is a finite group], [$H subset.eq G$ is a subgroup]),
  )[$|H|$ divides $|G|$]
]


== `#instance_declare` — typeclass instance clause

Default `carries` style (most general):

#instance_block("Real vector space on $RR^n$")[
  #instance_declare(
    [a #raw("Module") $RR$ structure],
    [$RR^n$],
    [addition is componentwise, scalar multiplication multiplies every
     coordinate by the scalar],
  )
]


== `#structure_instance_declare` — term-as-structure-instance

Useful when a term itself inhabits a structure type whose fields you want
to enumerate:

#instance_block("Trivial group structure on the singleton")[
  #structure_instance_declare(
    type: [Group],
    fields: (
      [`carrier := { star }`],
      [`mul := fun _ _ => star`],
      [`one := star`],
      [`inv := fun _ => star`],
      [the four group axioms hold trivially],
    ),
  )[the trivial group]
]


= Short bilingual-title aliases

These use the generic `entry` factory (with both Chinese and English
titles) and produce English-styled `env` strings. Useful in
mixed-language project contexts.


== `dfn` (Definition)

#dfn("非零向量", "Nonzero vector")[
  An element of a linear space that is not equal to the zero vector $bold(0)$.
]


== `thm` (Theorem)

#thm("拉格朗日定理", "Lagrange's theorem")[
  Let $G$ be a finite group and $H$ a subgroup. Then $|H|$ divides $|G|$.
]


== `axm` (Axiom)

#axm("选择公理", "Axiom of Choice")[
  Every non-empty family of non-empty sets admits a choice function.
]


== `ppt` (Property)

#ppt("零向量唯一", "Uniqueness of zero")[
  In any linear space, the zero vector is unique.
]


== `xmp` (Example)

#xmp("$RR^2$", "$RR^2$")[
  The plane $RR^2$ is a 2-dimensional $RR$-linear space.
]


== `rmk` (Remark, no background)

#rmk("注", "Remark")[
  Short aliases are convenient for terse documents but the long-form
  commands remain the recommended style for any work intended for
  long-term maintenance.
]


= End
