// FulcrumDemoCN.typ
//
// 新中文 (FulcrumCN) CNL 模板的演示文档。
// 编译方式 (在仓库根目录运行):
//   typst compile FulcrumDemoCN.typ FulcrumDemoCN.pdf
//
// 本文档展示:
//   - 12 个 *条目 命令: 定义条目 / 公理条目 / 引理条目 / 定理条目 / 推论条目
//                      性质条目 / 注条目 / 例条目 / 反例条目
//                      构造条目 / 证明条目 / 题目条目
//   - 5 个 *子句 命令: 定义子句 / 递归定义子句 / 结构子句 / 结构实例子句 / 定理子句
//   - 多子句同条目场景
//   - 子句各种可选参数组合 (条件 / type / 记号 / isPredicate)
//
// 旧中文命令 (#定义 / #定理 / #结构 / ...) 不在此展示, 它们仍可正常使用
// (在 FulcrumCN_old.typ 中实现, 通过 Fulcrum.typ re-export 暴露)。


#import "Fulcrum.typ": *

#show: FulcrumCN

#set document(title: "Fulcrum 新中文 CNL 模板 — 命令演示")

#align(center)[
  #text(size: 1.6em, weight: "bold")[
    Fulcrum 新中文 CNL 模板 \ 命令演示
  ]
  #v(0.5em)
  #text(size: 0.9em, fill: gray)[
    本文档展示 FulcrumCN.typ 的全部 12 个 \*条目 + 5 个 \*子句 的用法
  ]
]

#v(1em)


= 设计概览

新中文模板把 CNL 写作分成两层:

- *条目 (\*条目)*: 颜色框、标题、计数器、贡献者、uuid。一个条目内可放多个子句。
- *子句 (\*子句)*: 子句负责具体的 CNL 文字 (设…/定义…为…/记作…/则…)。

调用约定:

- 所有"必填"参数都是 *named* (主体: ..., 内容: ..., 结论: ...), 顺序自由
- 可选参数 (条件 / type / 记号 / isPredicate / \*style) 不传就走默认
- 一个条目里可以放多个子句, 各子句独立处理

接下来逐个展示。


= 12 个 \*条目

下面每个条目用一个最简单的 *定理子句* 或字面 body 占位, 主要看*框*的颜色、env 名、计数器是否独立。


== 定义条目 (绿)

#定义条目("线性空间", "Linear Space")[
  #定理子句(结论: [一个携带加法和数乘运算并满足若干公理的代数结构。])
]


== 公理条目 (黄)

#公理条目("选择公理", "Axiom of Choice")[
  #定理子句(结论: [非空集合族的笛卡尔积非空。])
]


== 引理条目 (蓝)

#引理条目("Zorn 引理", "Zorn's Lemma")[
  #定理子句(
    条件: ([$P$ 是非空偏序集], [$P$ 中每条链都有上界]),
    结论: [$P$ 含有极大元],
  )
]


== 定理条目 (蓝, 与引理共享 theorem 计数器)

#定理条目("有限维表示完全可约", "Maschke")[
  #定理子句(
    条件: ([$G$ 是有限群], [$KK$ 是特征不整除 $|G|$ 的域]),
    结论: [$G$ 的每个有限维 $KK$-表示都完全可约],
  )
]


== 推论条目 (蓝, 同定理/引理共享 theorem 计数器)

#推论条目("特征零有限群表示完全可约", "Maschke (char-zero corollary)")[
  #定理子句(
    条件: ([$G$ 是有限群], [$KK$ 是特征零的域]),
    结论: [$G$ 的每个有限维 $KK$-表示都完全可约],
  )
]


== 性质条目 (品红)

#性质条目("线性空间的零向量唯一", "uniqueness of zero vector")[
  #定理子句(
    条件: ([$V$ 是线性空间]),
    结论: [$V$ 中存在唯一的零向量 $bold(0)$],
  )
]


== 注条目 (橙, remark 风格)

#注条目("关于零向量的记号", "on the zero-vector notation")[
  本文档统一用 $bold(0)$ 表示线性空间的零向量, 与数 $0 in KK$ 区分;
  在不引起混淆时也可省去粗体。
]


== 例条目 (深紫)

#例条目("$RR^n$ 是 $RR$-线性空间", "$RR^n$ as a real vector space")[
  $RR^n$ 配以分量加法和分量数乘构成 $RR$-线性空间, 其零向量是
  $bold(0) = (0, ..., 0)$。
]


== 反例条目 (红)

#反例条目("$ZZ$ 不是 $RR$-线性空间", "$ZZ$ is not a real vector space")[
  $ZZ$ 上无法定义 $RR$ 上的数乘 (例如 $0.5 dot 1 in.not ZZ$),
  所以 $ZZ$ 不是 $RR$-线性空间。
]


== 构造条目 (灰, proof 风格)

#构造条目("构造商空间", "quotient space construction")[
  设 $W subset.eq V$ 是 $KK$-线性空间 $V$ 的子空间。
  在 $V$ 上定义等价关系 $u tilde v$ 当且仅当 $u - v in W$。
  令 $V \/ W := V \/ tilde$, 配以加法 $[u] + [v] := [u + v]$
  和数乘 $a [u] := [a u]$。
]


== 证明条目 (灰)

#证明条目("零向量唯一性", "uniqueness of zero vector")[
  设 $bold(0)_1, bold(0)_2$ 都是零向量, 则
  $bold(0)_1 = bold(0)_1 + bold(0)_2 = bold(0)_2$。
]


== 题目条目 (蓝, problem 风格)

#题目条目("", "")[
  设 $V$ 是有限维 $KK$-线性空间, $T : V -> V$ 是线性变换。
  证明 $T$ 是单射当且仅当 $T$ 是满射。
]


= 5 个 \*子句

接下来每个子句各展示几种参数组合。


== `#定义子句` — 普通定义

最小用法 (只传必填参数):

#定义条目("非零向量", "nonzero vector")[
  #定义子句(
    主体: [非零向量],
    内容: [线性空间中不等于零向量 $bold(0)$ 的向量],
  )
]

带条件:

#定义条目("线性无关", "linear independence")[
  #定义子句(
    条件: ([$V$ 是 $KK$-线性空间], [$bold(v)_1, ..., bold(v)_n in V$]),
    主体: [$bold(v)_1, ..., bold(v)_n$ 线性无关],
    内容: [由 $sum_(i=1)^n a_i bold(v)_i = bold(0)$ 蕴含 $a_1 = ... = a_n = 0$],
    isPredicate: true,
  )
]

带 type 注解 + 记号:

#定义条目("张量积空间", "tensor product space")[
  #定义子句(
    条件: ([$V, W$ 是 $KK$-线性空间]),
    主体: [$V$ 与 $W$ 的张量积],
    type: [$KK$-线性空间],
    内容: [由形如 $bold(v) times.o bold(w)$ 的元素生成, 满足双线性关系],
    记号: [$V times.o_KK W$],
  )
]


== `#递归定义子句` — 归纳/递归定义

类型情形 (枚举构造子, 含 type 注解):

#定义条目("自然数", "natural numbers")[
  #递归定义子句(
    主体: [自然数],
    type: [类型],
    构造子: (
      (name: [zero], type: [自然数]),
      (name: [succ], type: [自然数 -> 自然数]),
    ),
  )
]

谓词情形:

#定义条目("可由 ${a, b}$ 生成的子幺半群", "submonoid generated by $\{a, b\}$")[
  #递归定义子句(
    条件: ([$M$ 是幺半群], [$a, b in M$]),
    主体: [$x in M$ 在 $chevron.l a, b chevron.r$ 中],
    isPredicate: true,
    构造子: (
      [$x = 1_M$],
      [$x = a$ 或 $x = b$],
      [$x = y dot z$, 其中 $y, z in chevron.l a, b chevron.r$],
    ),
  )
]


== `#结构子句` — 结构体类型定义

无继承的最简结构:

#定义条目("半群", "semigroup")[
  #结构子句(
    主体: [半群],
    成员: (
      (name: [载体], value: $M$),
      (name: [乘法], value: $dot : M \* M -> M$),
      (name: [结合律], value: $forall a, b, c in M. (a dot b) dot c = a dot (b dot c)$),
    ),
    记号: $(M\, dot)$,
  )
]

带继承 (Group 继承自 Monoid):

#定义条目("群", "group")[
  #结构子句(
    主体: [群],
    继承: ([幺半群 $(M\, dot\, 1)$]),
    成员: (
      (name: [逆元运算], value: $"inv" : M -> M$),
      (name: [左逆律], value: $forall a in M. "inv"(a) dot a = 1$),
    ),
    记号: $(G\, dot\, 1\, "inv")$,
  )
]


== `#结构实例子句` — 结构体的具体实例

#定义条目("整数加法群", "additive group of integers")[
  #结构实例子句(
    主体: [$ZZ$ 上的加法群],
    类别: [群],
    成员: (
      (name: [载体], value: $ZZ$),
      (name: [乘法], value: [整数加法 $+$]),
      (name: [单位元], value: $0$),
      (name: [逆元], value: $n |-> -n$),
    ),
    记号: $(ZZ\, +\, 0\, -)$,
  )
]


== `#定理子句` — 唯一定理类子句

无条件 (直接结论):

#推论条目("循环群都是阿贝尔群", "cyclic groups are abelian")[
  #定理子句(结论: [所有循环群都是阿贝尔群])
]

带条件:

#定理条目("拉格朗日定理", "Lagrange")[
  #定理子句(
    条件: ([$G$ 是有限群], [$H subset.eq G$ 是子群]),
    结论: [$|H|$ 整除 $|G|$],
  )
]


= 多子句同条目场景

一个条目内可以放多个子句, 子句之间可以加普通文字、列表、空行。


== 一个性质条目内挂两条相关性质

#性质条目("零元素的吸收律与加法消去律", "absorption + cancellation")[
  #定理子句(
    条件: ([$V$ 是线性空间], [$bold(v) in V$]),
    结论: [$0 dot bold(v) = bold(0)$],
  )
  另外, 加法的消去律也成立:
  #定理子句(
    条件: ([$V$ 是线性空间], [$bold(u), bold(v), bold(w) in V$]),
    结论: [若 $bold(u) + bold(v) = bold(u) + bold(w)$, 则 $bold(v) = bold(w)$],
  )
]


== 一个定义条目挂多条相关定义

#定义条目("子线性空间相关概念", "on subspaces and span")[
  #定义子句(
    条件: ([$V$ 是 $KK$-线性空间], [$W subset.eq V$]),
    主体: [$W$ 是 $V$ 的子线性空间],
    isPredicate: true,
    内容: [$W$ 在 $V$ 的加法和数乘下封闭, 且 $bold(0) in W$],
  )
  此外:
  #定义子句(
    条件: ([$V$ 是 $KK$-线性空间], [$S subset.eq V$]),
    主体: [$S$ 张成的子空间],
    type: [$V$ 的子空间],
    内容: [$S$ 中元素的所有有限线性组合的集合],
    记号: [$"span"(S)$],
  )
]


= 完
